







development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: startup_development
  pool: 5

  username: postgres
  password: alpha12345


test:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: startup_test
  pool: 5
  username: postgres
  password: alpha12345


production:
  <<: *default
  database: <%= ENV['RDS_DB_NAME'] %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  PORT: <%= ENV['RDS_PORT'] %>