







development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: startup_development
  pool: 5

  username: site
  password: alpha123


test:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: startup_test
  pool: 5
  username: site
  password: alpha123


production:
  adapter: postgresql
  encoding: unicode
  database: startup_production
  pool: 5
  username: site
  password: alpha123